### ISSUE TITLE
Console instantly crashed when opened

### ISSUE THREAD

**Issue by Coinmaster123456** [devinacker/UnrealKey#9]

**Comment by Coinmaster123456** [comment]
sorry forgot bout that

**Comment by Coinmaster123456** [comment]
![image](https://user-images.githubusercontent.com/70707774/150802812-6ac0b591-0c3e-4d7d-a4b3-3a107365d030.png)
Anyways it won't catch the key of Witch It

**Comment by Coinmaster123456** [comment]
![image](https://user-images.githubusercontent.com/70707774/150803663-c60831f3-14f8-4392-93cd-e0bd3c9d7a94.png)
When running without steam

**Comment by AppleCanon** [comment]
on a unrelated note, how do you even use this?
